[build-system]
requires = ["setuptools >=42", "setuptools_scm[toml] >=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pytest_localserver/_version.py"

[tool.black]
target-version = ['py35']
line-length = 120
