name: Run tests with tox

on:
  - push
  - pull_request

jobs:
  build:
    name: 'Python runtime ${{ matrix.versions.python }}'
    runs-on: '${{ matrix.versions.os || matrix.os }}'
    # https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/
    if: >
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      matrix:
        # Not all Python versions are available for linux AND x64
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        os: ['ubuntu-latest']
        # The forced pytest versions correspond with the lower bounds in tox.ini
        versions:
        - python: '3.7'
          min-deps: '--force-dep pytest==4.6'
          os: 'ubuntu-22.04'
        - python: '3.8'
          min-deps: '--force-dep pytest==4.6'
        - python: '3.9'
          min-deps: '--force-dep pytest==4.6'
        - python: '3.10'
          min-deps: '--force-dep pytest==6.2.4'
        - python: '3.11'
          min-deps: '--force-dep pytest==6.2.4'
        - python: '3.12'
          min-deps: '--force-dep pytest==6.2.4'
        - python: '3.13'
          min-deps: '--force-dep pytest==6.2.4'
        - python: '3.14'
          min-deps: '--force-dep pytest==7.3.2'
        - python: 'pypy-3.7'
          min-deps: '--force-dep pytest==4.6'
          os: 'ubuntu-22.04'
        - python: 'pypy-3.8'
          min-deps: '--force-dep pytest==4.6'
        - python: 'pypy-3.9'
          min-deps: '--force-dep pytest==4.6'
      fail-fast: false

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.versions.python }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.versions.python }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: tox -vv -e py,py-smtp
    - name: Test with tox with forced minimum dependencies
      if: matrix.versions.min-deps
      run: tox -vv -e py,py-smtp ${{ matrix.versions.min-deps }}
